### PR TITLE
Upgrade CTS API to v2 

### PR DESCRIPTION
**Pull request by adriancofie**
# Description

https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-527

* Adds middleware
 #416

* Adds fetchers for v2
#426
#409
#421
#410
#410
#417
#422
#418
#418
#444
#444
#419
#419
#420
#423
#423
#425
#425
#443
#424
#424

* Misc
  #486
  #485
  #412
  #80

* Updates ResultsPage
#392
#432
#403
#447
#465
#342
#475
#341
#480
#505
#446

### CODE REVIEW

**Comment by adriancofie** [comment]
For testing / re-testing purposes the following can be used as a general guide:

Front-Facing
--------
Advanced Form Drug field is not limiting displayed results to 10  #485
The app should not worry about the URL #80
Implement Print Checkboxes on Results Page #342
Refactor CTS Pager component #341
Location is appearing blank for a trial on Search Results page on page 728 on local host #505
 Out-of-bounds page number displays blank screen #489
Error Page - Use Correct Form Type on Start Over #200 
Update zip to ZIP in all Zip Code references #193
Trial description shows blank page instead of invalid criteria #494


Backend / Refactoring
____
Change the CTS.Print/GenCache request #446
Remove Unused Lookup Hooks #412
Clinical Trials API v2 returns duplicates for Interventions endpoint requests #486
Change ResultsListItem to use Location Data from Search Criteria Object #403
Pull out degreeToRadian() function from isWithinRadius #432
Remove the Title Caching on ResultsListItem and Trial Description Page #447
Update print options to use regular checkbox #480
Console Error - "Cannot update a component 'StateProvider' while rendering a different component" #465
Remove clearForm dispatch from ResultsPage #483
Remove 'no results' div from Results Page Header #196

**Comment by alinai** [comment]
@sarinapadilla , the pager on https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-527 looks like the pager we have on DLPs. Is it expected? Also, we get the following error page on entering the invalid page number (url: https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-527/r?loc=0&pn=742&rl=1). Please confirm if this is the kind of error page we are expecting on react. On Prod we get a blank white page (url: https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?loc=0&pn=745&rl=1).

**Comment by alinai** [comment]
@adriancofie , please see the comment on (#505 )

**Comment by alerosad** [comment]
@alinai for the invalid page number error page, it seems to be fine since https://github.com/NCIOCPL/clinical-trials-search-app/pull/500 was what was approved by UX and Paul when he merged it. Seems like we don't want what was on prod, which was the blank page, going off pr-500.

**Comment by alinai** [comment]
@adriancofie , @sarinapadilla , Shouldn't "ZipCode" field be working now? For all valid Zipcode such as "20850", first time when we enter valid "Zipcode" we get validation error message and then if we clear the value (valid zipcode) from the Zipcode field and then re-enter the same value (same valid Zipcode) we get the invalid parameter page. 

@adriancofie , please see my comment on #193

**Comment by alinai** [comment]
> @alinai for the invalid page number error page, it seems to be fine since #500 was what was approved by UX and Paul when he merged it. Seems like we don't want what was on prod, which was the blank page, going off pr-500.

Thanks @alerosad for confirming,

**Comment by alinai** [comment]
@sarinapadilla, please confirm if the behavior on https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-527/r?hos=NCI%20-%20Center%20for%20Cancer%20Res&loc=3&rl=2 or https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?hos=NCI%20-%20Center%20for%20Cancer%20Res&loc=3&rl=2 is correct? 

Note: Changed Hospital/Institution from "Research" to "Res" in the url.

**Comment by adriancofie** [comment]
> @sarinapadilla, please confirm if the behavior on https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-527/r?lo=GlaxoSmith&loc=0&rl=2 or https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?lo=GlaxoSmith&loc=0&rl=2 is correct?
> 
> Note: Changed Lead Organization from "GlaxoSmithKline" to "GlaxoSmith" in the url. React app returns "No clinical trials matched" error page and Prod returns search results.

I checked the POST request/ response and  we're sending over

`lead_org._fulltext : "GlaxoSmith"` and it's returning a 200  response with 0 results, so I think this is on their end.

**Comment by alinai** [comment]
@adriancofie , Noticed that on typing three characters in the Drug family field, "no results" appears for a second or two and then the drop-down shows results. Same is happening for other fields user needs to enter 3 characters for drop-down appears.

image

image

**Comment by alinai** [comment]
@sarinapadilla . @adriancofie . noticing that the autosuggest in the drop-down in "Primary Cancer Type/Condition" field in Advanced Search page is displaying "Carcinoma" for different cancer types in react-app in place of "Cancer" in Prod. Is it expected?

image

image

**Comment by alinai** [comment]
@adriancofie , the autosuggest for "Stage" also looks different from Prod for a particular "Primary Cancer Type/Condition"

image
image

**Comment by alinai** [comment]
@sarinapadilla , When I entered "Adams Cancer Center" to the "At Hospital/Institution" field, Prod and react returned same kind of result but none of them returns results using the filter  "Adams Cancer Center". I don't see any locations near me in the search results. Do we need to enter any ticket for this as it is an existing issue?

image
image

**Comment by alinai** [comment]
@adriancofie , Not seeing "Drug Family" in parentheses and other names in the autosuggest for Drug/Drug Family field in react-app. Is it expected?

image

image

**Comment by alinai** [comment]
@adriancofie , Also not seeing "Other Names" in the autosuggest for "Other Treatments" field in react-app. Is it expected?
image
image

**Comment by alinai** [comment]
@adriancofie , I can see Trial Phase and Trial Type in the Print page but not on the Trial Description/View page. Is it expected for now?

**Comment by alinai** [comment]
@adriancofie , @sarinapadilla , when I search with "NCI-2014-01507" in Trial ID field, I get one result both in react-app and Prod. When I search with"NCI-2014-01507" in "Keywords/Phrases" field, I get one result in react-app and 15 results in Prod. Please confirm which behavior is correct.

**Comment by adriancofie** [comment]
> @sarinapadilla , When I entered "Adams Cancer Center" to the "At Hospital/Institution" field, Prod and react returned same kind of result but none of them returns results using the filter "Adams Cancer Center".

@alinai  Can you create a ticket for this one? And add the following image:


Screen Shot 2022-06-13 at 11 45 29

**Comment by alinai** [comment]
> > @sarinapadilla , When I entered "Adams Cancer Center" to the "At Hospital/Institution" field, Prod and react returned same kind of result but none of them returns results using the filter "Adams Cancer Center".
> 
> @alinai Can you create a ticket for this one? And add the following image:
> 
> Screen Shot 2022-06-13 at 11 45 29

@adriancofie , Entered https://github.com/NCIOCPL/clinical-trials-search-app/issues/531 for the above issue on Prod.

**Review by arcepaul — APPROVED** [review]

**Pull request merged**
