### PR TITLE
#201 Modify Search from Trial Details Page

### LINKED ISSUE #201: Modify search from Trial Details Page
Can we please add a modify search link on the Trial Details page?  It should be on the same line as Start Over, with an option to "Modify Search Criteria" and lead us back to the advanced form with the search terms pre-populated.  (it should look like it does on the search results page, below the search accordion, with both options on the same line "Start Over | Modify Search Criteria")

### PR DESCRIPTION
**Pull request by alerosad**
- added modify search button to Trial Description Page

(Closes #201 )

### CODE REVIEW

**Review by adriancofie — APPROVED** [review]

**Review by adriancofie — CHANGES_REQUESTED** [review]
Can you add a cypress scenario to the existing modify search ones to cover this?  @alerosad

**Comment by alerosad** [comment]
Yeah currently working on it @adriancofie, running into a weird issue where the fields are populated when cypress clicks modify search. Not sure why, since it works fine when I manually test it

**Comment by alinai** [comment]
@alerosad , which environment are we testing this ticket?

**Comment by alinai** [comment]
> https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-521/

Thanks @alerosad

**Comment by alinai** [comment]
Currently the "Start Over" link is wrapping to the next line after the "|" in "This clinical trial matches: "all trials"" at desktop breakpoint. Screen-shot is attached. 
@mworrest, can you please confirm if it looks good to you?

image

**Comment by SupriyaSaxena0605** [comment]
@mworrest Also, this issue is happening on both FF and Chrome

**Comment by mworrest** [comment]
It should be fixed to match the results page and the lighter link colors need to be our default link color #2b7bba. Why is #2ba6cb being used for links? It's not compliant.

**Comment by alinai** [comment]
> It should be fixed to match the results page and the lighter link colors need to be our default link color #2b7bba. Why is #2ba6cb being used for links? It's not compliant.

Thanks @mworrest!

**Comment by alerosad** [comment]
will fix, thanks Michelle!

**Comment by alerosad** [comment]
@mworrest  I see that on the develop branch the link colors are set to be #2ba6cb for 'Start Over' while #2b7bba for 'Modify Search Criteria' and #2ba6cb for the clinical trial results links. I was going off those examples when adjusting the trial description page. Did you still want me to change the colors to be #2b7bba for the different link buttons?

**Comment by mworrest** [comment]
Yes, please change links to be #2b7bba. I don't know how they got changed to the new non-compliant blue color but that's incorrect.

**Comment by alerosad** [comment]
> Yes, please change links to be #2b7bba. I don't know how they got changed to the new non-compliant blue color but that's incorrect.

gotcha will do

**Comment by alinai** [comment]
@alerosad , I am seeing that the hover color for "Start Over" link is #2ba6cb. The hover color should be consistent for all links.
cc: @mworrest.

image
image

**Comment by alinai** [comment]
@mworrest , can you please confirm if the link colors and the link hover/active state colors look good to you? Thanks!
url: https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-521

**Comment by alinai** [comment]
@sarinapadilla , here is a requirement question. Should we see "Modify Search Criteria" on Trial Description page when we are performing default search? On Prod and react-app we do not see "Modify Search Criteria" on Search results page when we don't add filters to our search. I am wondering if we should see "Modify Search Criteria" on Trial Description page when we don't see it for default search (without filters) on Search Results page.

**Comment by sarinapadilla** [comment]
@alinai the current functionality on Prod is that the Modify Search Criteria link only displays on results pages when there are search criteria used, and does not display when just the default parameters are used. This is the correct functionality and should be the functionality for the Modify Search Criteria link on the view page!

**Comment by alinai** [comment]
> @alinai the current functionality on Prod is that the Modify Search Criteria link only displays on results pages when there are search criteria used, and does not display when just the default parameters are used. This is the correct functionality and should be the functionality for the Modify Search Criteria link on the view page!

Thanks @sarinapadilla for confirming. 
@alerosad , please take a look at the requirement confirmed by @sarinapadilla. FYI, we  are seeing the "Modify Search Criteria" on Trial Description page/View page for default search on React-app.

**Comment by alerosad** [comment]
should be good to go now, I also rebased with the new v2 changes on develop @alinai https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-521

let me know if there are any more issues with the PR, thanks!

**Comment by alinai** [comment]
> It should be fixed to match the results page and the lighter link colors need to be our default link color #2b7bba. Why is #2ba6cb being used for links? It's not compliant.

@alerosad , still the "Start Over" link is wrapping to the next line on Trial description page for default (without any filter) search. Please see the requirement for this provided by @mworrest. Thanks

**Review by arcepaul — APPROVED** [review]

**Pull request merged**
