### PR TITLE
(#514) Update Browser Title to Use siteName Parameter

### LINKED ISSUE #514: Update Browser Title to Use siteName Parameter
### Issue description
Previously, the org name that is appended to the browser title is hardcoded to be "- National Cancer Institute". The app should be updated to append the siteName parameter from the initialize function to the browser title instead (as the dictionaries and DLPs do) on all pages - search forms, results page, trial description pages, no results found, and invalid criteria.

> **ESTIMATE** TBD

### What's the expected change?
- The app appends "- NCI" to the browser title by using the siteName parameter from the initialize function.

### What's the current functionality?
- The app appends "- National Cancer Institute" to the browser title by hardcoding it.

### What's the updated acceptance criteria?
```gherkin
  Scenario: Page Load Analytics fires when a user views a Basic Search form
    Given "ctsTitle" is set to "Find NCI-Supported Clinical Trials"
    And "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "siteName" is set to "NCI"
    And "channel" is set to "About Cancer"
    And "analyticsPublishedDate" is set to "02/02/2011"
    And "analyticsName" is set to "Clinical Trials"
    When the user navigates to "/"
    Then the page title is "Find NCI-Supported Clinical Trials"
    And browser waits
    Then there should be an analytics event with the following details
      | key                                  | value                                                          |
      | type                                 | PageLoad                                                       |
      | event                                | ClinicalTrialsSearchApp:Load:BasicSearch                       |
      | page.name                            | www.cancer.gov/  					      |
      | page.title                           | Find NCI-Supported Clinical Trials                             |
      | page.metaTitle                       | Find NCI-Supported Clinical Trials - NCI                       |
      | page.language                        | english                                                        |
      | page.type                            | nciAppModulePage                                               |
      | page.channel                         | About Cancer                                                   |
      | page.contentGroup                    | Clinical Trials                                                |
      | page.publishedDate                   | 02/02/2011                                                     |
      | page.additionalDetails.analyticsName | Clinical Trials                                                |
      | page.additionalDetails.formType      | basic                                                          |
```

``` gherkin
Scenario: Page Load Analytics fires when a user views an Advanced Search form
    Given "ctsTitle" is set to "Find NCI-Supported Clinical Trials"
    And "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "siteName" is set to "NCI"
    And "channel" is set to "About Cancer"
    And "analyticsPublishedDate" is set to "02/02/2011"
    And "analyticsName" is set to "Clinical Trials"
    When the user navigates to "/advanced"
    Then the page title is "Find NCI-Supported Clinical Trials"
    And browser waits
    Then there should be an analytics event with the following details
        | key                                  | value                                                       |
        | type                                 | PageLoad                                                    |
        | event                                | ClinicalTrialsSearchApp:Load:AdvancedSearch                 |
        | page.name                            | www.cancer.gov/advanced            			     |
        | page.title                           | Find NCI-Supported Clinical Trials - Advanced Search        |
        | page.metaTitle                       | Find NCI-Supported Clinical Trials - Advanced Search - NCI  |
        | page.language                        | english                                                     |
        | page.type                            | nciAppModulePage                                            |
        | page.channel                         | About Cancer                                                |
        | page.contentGroup                    | Clinical Trials                                             |
        | page.publishedDate                   | 02/02/2011                                                  |
        | page.additionalDetails.analyticsName | Clinical Trials                                             |
        | page.additionalDetails.formType      | advanced                                                    |
```

### Additional details / screenshot
- Screenshot

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

### PR DESCRIPTION
**Pull request by alerosad**
- app now uses siteName Param when constructing browser title, rather than the hardcoded version
- updated integration tests
- updated siteName Param to be NCI

Closes #514

### CODE REVIEW

**Comment by alerosad** [comment]
https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-515

**Review by mworrest — CHANGES_REQUESTED** [review]
I'm not seeing the addition of "-NCI" on the browser title of trial description pages: https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-515/v?a=45&id=NCI-2021-03472&loc=0&pn=669&rl=1

Screen-Shot-2022-05-03-at-10 16 43-AM-(2)

**Comment by alerosad** [comment]
ah ok, must have missed it, i'll go ahead and make that change

**Comment by alinai** [comment]
cc: @SupriyaSaxena0605

**Comment by alinai** [comment]
@blairl-nih , Thanks for confirming that Trial Description Page and Check for Updates page are same. 
@alerosad , @sarinapadilla , verified that the "-NCI" is appearing in browser title on Basic Search Form, Advanced Search Form, Search Results page and Trial Description page. 
**Requirement Question:** 
@sarinapadilla, On Prod,  I am not seeing the org name "- National Cancer Institute".  appended to the browser title of the Print Page. Do we want "-NCI" to be appended to the browser title after this change?

**Comment by sarinapadilla** [comment]
@alinai I believe we already discussed this, but putting it here for sanity - we are not going to append the org name to the print page!

**Comment by SupriyaSaxena0605** [comment]
@sarinapadilla the Analytics look good on console for both Basic and Advanced Search form. All looks good on react-app-dev.

**Comment by sarinapadilla** [comment]
@alerosad I checked the title tags and they're all updated to using the siteName param. This ticket looks good to me!

**Review by adriancofie — APPROVED** [review]

**Comment by alerosad** [comment]
For the LocationLimitedToVa.feature integration test, I'm currently running into this issue 
image
I went through the failing test manually and ran into a similar issue. Currently working on trying to figure out the issue

**Comment by adriancofie** [comment]
@alerosad It's complaining about the following missing :[Error: ENOENT: no such file or directory, access '/home/runner/work/clinical-trials-search-app/clinical-trials-search-app/support/mock-data/v2/trials/lead_org__m d anderson cancer center__10.json'] 

I had a quick look and it doesn't exist in this branch OR develop.  The file name also has weird spacing so there may be a disconnect somewhere

**Comment by alerosad** [comment]
https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-515

**Review by arcepaul — APPROVED** [review]

**Review by mworrest — APPROVED** [review]
Looks like "- NCI" is appended to the browser title. Thanks.

Screen-Shot-2022-06-21-at-2 43 13-PM-(2)

**Pull request merged**
