### PR TITLE
(#561) Clicking a help (?) link is returning a blank page

### LINKED ISSUE #561: Viewing a URL that does not resolve to an app path displays a blank page
### Issue description
Whenever a URL that does not resolve to one of our app paths, the app displays a blank page. It should actually display a Page Not Found.

This was discovered by the help links on the search form opening a blank page when clicked. The specific issue with the help links has been solved by creating the Help Finding NCI-Supported Clinical Trials page. A separate ticket (https://github.com/NCIOCPL/clinical-trials-search-app/issues/573) has been created to update the help link anchor links.

> **ESTIMATE** TBD

### Steps to reproduce the issue
1.  Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/foo

### What's the expected result?
- A 404 page should display.

### What's the actual result?
- A blank page displays.

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #561

* Added route handler and view `PageNotFound` for paths not found in app
* Added scenario to integration test for non-existent path

### CODE REVIEW

**Review by bryanpizzillo — APPROVED** [review]
Looks good to me from a code standpoint. QA needs to test.

**Comment by sarinapadilla** [comment]
@alinai when you test, note that the styles for this PNF are slightly different than the ones on Prod, and that is okay! We will investigate if it doesn't not look right after launch.

**Comment by sarinapadilla** [comment]
Also this looks good to me

**Review by alerosad — APPROVED** [review]

**Comment by alinai** [comment]
@sarinapadilla , I have confirmed the AC of this ticket with @seyilonge-nci.  Based on that verified the following:
1. https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-568/bbvcxv takes us to the following 404 page
image

2. On clicking 'help' links we will continue seeing the blank white page with the text "Not found" until we are on ODE.
3. The PNF is not showing "-NCI" in the browser title. Confirmed with @seyilonge-nci that the Page Not Found, is mirrored after CTL Prod which does not have "-NCI" appended to the browser title 
Prod url: https://www.cancer.gov/about-cancer/treatment/clinical-trials/disease/former 

Working as expected on react-app. Thanks @seyilonge-nci for helping me with the testing!

**Comment by alinai** [comment]
@seyilonge-nci, please link this ticket to the new ticket that you will create for the help link issue on react-app. Thanks!!

**Comment by sarinapadilla** [comment]
@alinai the PNF should show - NCI in the browser title, as we have that on the PNF for Drupal 404s (this is a bug on the listing app). If that's an easy fix to implement then please update @seyilonge, otherwise I'll create a ticket for it to address after launch!

**Pull request merged**
