### PR TITLE
(#549 | #550) Icons not displayed on search and view pages

### LINKED ISSUE #549: Print icon is not displaying on view pages
### Issue description
The print icon on the print button that displays on view pages is not displaying.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/v?id=NCI-2014-01507&loc=0&rl=1

### What's the expected result?
- The print icon should display on the print button.

### What's the actual result?
- The print icon does not display on the print button.

### Additional details / screenshot
ODE:
viewpageODE

PROD:
viewpagePROD

### Related Tickets
* Issue #9999
* Issue #9999

### LINKED ISSUE #550: The image for the "Have a question?" delighter is not displaying
### Issue description
The image that is associated with the "Have a question?" delighter is not displaying on the ODE.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/

### What's the expected result?
- The "Have a question?" delighter has an image

### What's the actual result?
- The image for the delighter does not display.

### Additional details / screenshot
ODE:
searchformODE

PROD:
viewpagePROD

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by seyilonge-nci**
(#549)  Print icon is not displaying on view pages 

Closes #549 
* Removed quotes and whitespace from url for `background-image` in stylesheet
* Put quotes back in
* Added width property for print icon

---

(#550) The image for the "Have a question?" delighter is not displaying

Closes #550 
* Updated stylesheet to include declarations from `common.css` for live help icon missing in ODE

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@alinai Please review https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-551/v?id=NCI-2014-01507&loc=0&rl=1

**Comment by seyilonge-nci** [comment]
Issue fixed now. @alinai please review once more.

**Comment by alinai** [comment]
Print icon is displaying on the view page on the ODE. The image for the "Have a question?" delighter is displaying on the ODE on Basic Search page, Advanced Search page, Results page, View page, Invalid param page and No Trials Found page. Thanks @seyilonge-nci .

**Comment by alinai** [comment]
@seyilonge-nci , @KateMashkinaNIH , Double delighters appears at mobile breakpoint in the invalid param page - Ticket has been entered https://github.com/NCIOCPL/clinical-trials-search-app/issues/552

**Review by KateMashkinaNIH — APPROVED** [review]

**Pull request merged**
